trigger:
- master

pr:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- script: |
    npm install
  displayName: 'scrip blah'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  artifact: drop

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure Web App Deploy: hackhlth-backend'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(1)(8b9edd9a-2350-4085-836e-6fb70c391652)'
    appType: 'webAppLinux'
    WebAppName: 'hackhlth-back'
    package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    RuntimeStack: 'NODE|12-lts'
    StartupCommand: 'npm run start'